### PR TITLE
additional font info

### PR DESCRIPTION
**Pull request by tomByrer**
+ homepage, gh repo, & version; would be useful if web versions are needed, or to see if more current versions are available.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
I really like the idea.  I am thinking of transitioning to small symbol icons instead of text links.  Not all projects are open source so this will not apply to all, but I agree, this would be useful information.

**Comment by tomByrer** [comment]
I like the icon idea.  I'm partial to SVG; easier to scale.

**Comment by chrissimpkins** [comment]
have any ideas?  I was considering something simple like colored flat square buttons with a letter for the links.

**Comment by tomByrer** [comment]
I like icons: http://www.jsdelivr.com/

**Comment by chrissimpkins** [comment]
haven't forgotten about this.  also added you to contributors list.

**Comment by tomByrer** [comment]
Np; figured my request was a "keep in mind when you refactor".
Take your time.

**Comment by chrissimpkins** [comment]
Tom, are you willing to do some work on this font info PR so that we can merge it as part of the (relatively significant) updates coming to the galleries?

**Pull request closed without merging**
