### PR TITLE
Add Roboto Mono

### PR DESCRIPTION
**Pull request by alebcay**

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks for contributing this Caleb.  I will merge it in today.

**Comment by chrissimpkins** [comment]
for the purposes of the image that I generate for it, do you generally use Regular or one of the other weights?

**Comment by alebcay** [comment]
I personally usethe Regular weight.

**Comment by chrissimpkins** [comment]
sounds good.  thanks much!

**Comment by chrissimpkins** [comment]
merged and added to the main gallery.  Thanks again!

**Pull request merged**
