### PR TITLE
data files

### PR DESCRIPTION
**Pull request by braver**
I've added a data folder and folders for all the fonts folders (and a little shell script to update the folders). Currently I'm splitting up the fonts.json I sent you earlier across these folders, to make it easier to work with. 

As I have some data on commercial fonts, for completeness sake I'm adding those too. Of course we can't redistribute font files or screenshots, but I think we might want to have them in here if only by name.

I'll add to this PR as I go through my files.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Excellent, look forward to working on this.

**Comment by braver** [comment]
Alrighty... I've added all the data I have available and a schema to serve as a template and to validate the data against. A bunch of data files cover commercial fonts, or bitmap fonts, that aren't included in the repository. But I think if we're collecting data it's better to be a bit completist about it. 

That said though, this isn't complete. For now, there are a few fonts I want to add to app.programmingfonts.org and a bunch of fonts I want to blog about. As I do so, I will add any data I collect to this project.

I love the idea of making an interactive font browser out of this. But the reality is that the weather is slowly getting better and I'm more inclined to go outside than to code up an application like that :sunglasses: I *am* thinking about it, but I don't expect much traction on this from my end right now.

**Comment by chrissimpkins** [comment]
> the weather is slowly getting better and I'm more inclined to go outside than to code up an application like that

^5  I hear you.  Sorry for the delay here

**Comment by chrissimpkins** [comment]
Haven't forgotten.

**Comment by braver** [comment]
Sure, no worries, take your time.

**Comment by chrissimpkins** [comment]
The reporting feature in this new tool might be useful for your site:

https://github.com/source-foundry/font-line

It reports font vertical metrics that are involved in line spacing.  I am considering a way to format output as JSON.  Let me know if you happen to use it and think that would be useful.

**Pull request closed without merging**
