### PR TITLE
Add common programming ligatures test line

### PR DESCRIPTION
**Pull request by kevinSuttle**
In response to #162

### CODE REVIEW

**Comment by chrissimpkins** [comment]
:+1:  will try to generate the images tomorrow so that we can see if the scripted image generator approach displays them.  Do you know which fonts in the main gallery include them?

**Comment by kevinSuttle** [comment]
Fira Code, Hasklig, and Monoid are the only 3 that I know of.

**Comment by chrissimpkins** [comment]
Looks great!

You can view the new images in the `ligatures` branch here:

https://github.com/chrissimpkins/codeface/tree/ligatures 

Let me know if these render how you expect them to appear and we will merge to master.  You are correct, Fira Code, Hasklig and Monoid are the only ones that appear to have ligatures in this collection.  If you know of any others out there, feel free to PR them in.

**Comment by kevinSuttle** [comment]
Nice! Now to delineate them. https://github.com/chrissimpkins/codeface/issues/162#issuecomment-317076222

**Comment by chrissimpkins** [comment]
How about this:

### Typeface Name [Ligature](#)

**Comment by kevinSuttle** [comment]
Ooh nice!

**Pull request merged**
