### PR TITLE
added pointfree font

### PR DESCRIPTION
**Pull request by wizawu**
Download from http://www.dafont.com/pointfree.font

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks! Interesting, I haven't seen these fonts in the i3project before.  This page says that they are not hinted:

https://code.google.com/p/i3project/wiki/Fonts 

Can you tell me what platform you are using this on and the size that you use?  The lack of hinting is likely to be an issue for developers on some platforms.

**Comment by wizawu** [comment]
I have been using it in VIM on Debian with xfce4 for a while. Size 10 is fine for me, but somehow it is a little bit small for others.
screenshot_2015-12-02_00-23-32

**Comment by chrissimpkins** [comment]
Comic Sans for code...

**Comment by wizawu** [comment]
Indeed :joy:

**Comment by wizawu** [comment]
You can just close it if this font doesn't meet your taste. It's better than hanging the PR here :)

**Comment by chrissimpkins** [comment]
planning to work on this over the weekend.  haven't had the time yet

**Comment by chrissimpkins** [comment]
Added and now available in the main gallery.  Thanks for the suggestion and PR!

**Comment by chrissimpkins** [comment]
added your name to the contributors list as well

**Comment by wizawu** [comment]
Thanks for the _Long Arm_ :sunglasses:

**Comment by chrissimpkins** [comment]
;)

**Pull request merged**
