### PR TITLE
Add Kawkab Mono

### PR DESCRIPTION
**Pull request by wizawu**
Hi, it's me again.
Just found a new font on [fontlibrary.org](https://fontlibrary.org/en/font/kawkab-mono). It's quite similar to _Source Code Pro_ except that it has a larger line height.
Hope that it is useful for you.

mono

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thank you very much!  I am updating the galleries this weekend and will include it.

**Comment by chrissimpkins** [comment]
This font is now included in the `development` branch and will be part of the next merge.  I'm working on several other additions to the gallery before we merge it.  

https://github.com/chrissimpkins/codeface/tree/development#kawkab-mono

Thanks for submitting it!

**Comment by chrissimpkins** [comment]
merged!

**Comment by wizawu** [comment]
:100:

**Pull request merged**
