### PR TITLE
Add Bront

### PR DESCRIPTION
**Pull request by chrismwendt**
The repository is located at https://github.com/chrismwendt/bront.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
thanks much!  I will merge it today

**Comment by chrissimpkins** [comment]
Added and you are included in the contributors list.  Thanks much for the PR!

**Comment by chrismwendt** [comment]
Great, thanks!

**Comment by chrissimpkins** [comment]
How did you make that diff image?  That is fantastic.  Would like to use that.

**Comment by chrismwendt** [comment]
The script is in my repo at

https://github.com/chrismwendt/bront/blob/89785af894459275c571815dd0e352d0b892e712/render.sh

(it's a link to a commit, just in case the script gets renamed)

**Comment by chrissimpkins** [comment]
This is great! Mind if I use it to create diffs for some of these typefaces vs. their origins?

**Comment by chrismwendt** [comment]
Sure, go ahead!

**Comment by chrissimpkins** [comment]
Thanks much!  Great fonts by the way.  I really like both of them.

**Comment by chrismwendt** [comment]
Thanks :smile:

**Pull request merged**
