### PR TITLE
add missing fonts

### PR DESCRIPTION
**Pull request by braver**
Adds
- Effects Eight: http://programmingfonts.org/post/108155366967/effects-eighty-effects-eighty-is-an-homage-to
- Fifteen: http://programmingfonts.org/post/105697177252/fifteen-fifteen-is-a-faux-bitmap-font-this
- Quinze: http://programmingfonts.org/post/108356936857/quinze-quinze-is-a-narrow-monospaced-font
- Generic Mono: http://programmingfonts.org/post/107484861287/generic-mono-a-generic-monospaced-font
- GNU Freefont: http://programmingfonts.org/post/105292943237/gnu-freefont-gnu-freefont-is-a-free-family-of
- GNU Unifont: http://programmingfonts.org/post/106597331097/gnu-unifont-this-version-provides-full
- Nova Mono: http://programmingfonts.org/post/108185612517/nova-mono-i-created-the-novacut-font-about
- VT323: http://programmingfonts.org/post/108945284232/vt323-this-font-was-created-from-the-glyphs

I don't have license files for Fifteen and Quinze but they're SIL OFL: https://fontlibrary.org/en/font/fifteen

(I standardized all file names in my repositories to make them easier to work with.)

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Thanks for all of these contributions @braver.  I will have a look and get them merged.  Will be in touch with any questions.

**Comment by chrissimpkins** [comment]
Responded to your email by the way.  Let me know if you have any more information about how you would like to collaborate.

**Comment by chrissimpkins** [comment]
Converting to an automated image generation approach that I hope to have implemented in the next week'ish.  Sorry for the delay.  I will get these merged as soon as it is available.

**Comment by chrissimpkins** [comment]
New gallery images are now merged. I will add these fonts over the weekend.  Thanks @braver

**Comment by chrissimpkins** [comment]
Do you mind pulling Unifont out of your PR Koen?  It is too large of a fileset to include in this collection.

**Comment by braver** [comment]
Sure, no problem. It *is* quite large (which is what you get for bitmap fonts I guess). It's a pretty cool project though, so perhaps the omission should be noted somewhere in the docs?

**Comment by chrissimpkins** [comment]
Sure, I will specify some inclusion criteria.  Trying to keep archive file size as small as we can.

**Comment by chrissimpkins** [comment]
Are any others in this set bitmaps?

**Comment by braver** [comment]
No, I don't think so.

**Comment by chrissimpkins** [comment]
thanks!

**Comment by chrissimpkins** [comment]
Any chance that you would be willing to split these fonts into individual PR's?  I will likely cherry pick a bit here and am ready to start including some.

**Comment by braver** [comment]
You could also just clone this branch somewhere and copy the files you want to your master clone. I don't  really care enough about getting my name in your git history to spend all night splitting this into separate PR's :wink:

**Comment by chrissimpkins** [comment]
Thanks

**Comment by chrissimpkins** [comment]
I don't use the git commit history to acknowledge contributors in this project in any case.  Your name is already on our contributors list.

**Comment by braver** [comment]
Ok, thanks. I just don't look forward to the hassle with git and everything to split out this PR. So, if you can manage it like this, that'd be easiest. If you need help, let me know.

**Comment by chrissimpkins** [comment]
It’s no problem, I can definitely do it.

**Comment by chrissimpkins** [comment]
The license that you included for Generic Mono does not appear to be for the correct set of fonts.  

https://github.com/chrissimpkins/codeface/blob/master/fonts/generic/license.txt

Do you have a link to the site where this is released?  I can access this via the link on your site but I don't find a release on the sites linked from that site.

**Comment by braver** [comment]
I think I originally got it from fontlibrary.org, but that site doesn't have this font anymore.

**Comment by chrissimpkins** [comment]
OK, thanks Koen.

**Pull request closed without merging**
